# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf528116ba99d233a479d053a62302ce76985224b06644f8656eaed4f65632516379890d9cb97f18458a2ff609a729be951a89f57e4023bf0f29f748622af893

test:
  secret_key_base: 64b79dd6942ed78c2b859ed832d1c81f7106bbf5c3ba54efdaa705ea5ecdd1b9ec183ce3404e682e553db97966f351b4563eb74ebd78733594f6d8c96dcde42f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
